### PR TITLE
Add GitHub eye candy

### PR DESCRIPTION
**Pull request by ThomDietrich**
😃 

Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)

### CODE REVIEW

**Comment by BClark09** [comment]
Hey @ThomDietrich! Syntax highlighting was left out of this file since there are only two types of line for a default file called by systemd: comments and assignments. Would it be misleading to imply you could have bash/shell script in this file? Alternatively, if this is just for Github, could we use. gitattributes? 

If you think not, I'll merge the PR. ☺️

**Comment by ThomDietrich** [comment]
Hey @BClark09, I didn't think this would be an issue. After some consideration I agree that not modifying the actual file is overall better. Let me draft two more commits (I'm too lazy to power up my git client :yum: )

**Comment by ThomDietrich** [comment]
@BClark09 wdyt?

**Comment by BClark09** [comment]
Awesome! Much appreciated @ThomDietrich, sorry for being picky! :smiley:

**Comment by BClark09** [comment]
:see_no_evil: I thought these changes only took place in master, which is why I merged, but turns out .gitattributes doesn't affect syntax hilighting in Github, it does in Gitlab though.

**Comment by BClark09** [comment]
Turns out the file needs to be indexed before updating to the new syntax highlighting.

What are your thoughts on using INI instead of Shell for the file:

https://github.com/BClark09/openhab-linuxpkg/blob/master/resources/etc/default/openhab2
https://github.com/BClark09/openhab-linuxpkg/blob/master/resources/systemd/openhab2.service

**Comment by ThomDietrich** [comment]
Yes I should have mentioned that. Takes a few minutes.

Ini looks indeed way better. I've checked a few settings in vim beforehand and ini didn't look good there. I should have checked on GitHub instead :see_no_evil: 

Go for it ;) Thanks!

**Comment by ThomDietrich** [comment]
Ini is btw also what I'm [using](https://github.com/openhab/openhabian/blob/master/.gitattributes) in openHABian and the indexing problem [tricked me once before](https://github.com/github/linguist/issues/3551) :smile:

**Pull request merged**
