### PR TITLE
Rename 'openhab' script to 'openhab-cli'

### PR DESCRIPTION
**Pull request by BClark09**
Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Comment by BClark09** [comment]
@ThomDietrich

**Comment by ThomDietrich** [comment]
Continuing from https://github.com/openhab/openhab-linuxpkg/issues/77
Lgtm. Let's also query @kaikreuzer because he was involved in all prior discussions.

**Comment by kaikreuzer** [comment]
Was I? I hardly remember the discussion, but openhab-cli is fine for me.

**Comment by ThomDietrich** [comment]
Hmmmmm ... well there was [one](https://github.com/openhab/openhab-linuxpkg/pull/78#issuecomment-323163953) comment 🙈

**Comment by BClark09** [comment]
I've been thinking, would it be worth moving openhab-cli to the openHAB distro? With a couple of line changes, the script _should_ work for MacOS.

**Comment by kaikreuzer** [comment]
So far the distro tries to be platform independent, so the very same should then also exist for Windows...

**Comment by BClark09** [comment]
Quite right, so if the openhab-cli might be something of value to all platforms, then we'd need to make a separate issue for a windows implementation. I guess this is currently what we're doing with the backup/restore scripts.

**Comment by kaikreuzer** [comment]
If we can manage to provide something like that for windows, it would be ok for me to move the tool to the distro, sure.

**Comment by tmrobert8** [comment]
fyi - I'd be happy to write the windows version if you want

**Pull request merged**
