### PR TITLE
Add clean functions to cli

### PR DESCRIPTION
**Pull request by BClark09**
- Added the commands:
   - `clean-cache` - Cleans the openHAB temporary folders.
   - `reset-config` - Reinstalls openHAB with default system configuration.
   - `reset-ownership` - Resets the ownership of openHAB directories.

- Alphabetised the order of the commands.

Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Comment by BClark09** [comment]
Hey @ThomDietrich 

I've added an initial "set ownership", do you think that setting the permissions would also be useful for the general cli?

**Comment by ThomDietrich** [comment]
After a quick review everything looks good I'd say. 👍
The command was primarily needed so that the group also has write permissions. In your scenario that is not needed. Thanks for including an overwrite option for openHABian.

**Comment by ThomDietrich** [comment]
One additional comment: I imagine some users will not know what these options do and when to use them. A few more lines of clarification would be good.

**Comment by BClark09** [comment]
Cheers @ThomDietrich, I've made some adjustments which meant removing the reset-config command. I noticed that if the user is on snapshot, and these are cleaned from the repository then the reinstallation will fail, putting the installation in a broken state. Will have to think about that a bit more.

**Pull request merged**
