### PR TITLE
Change deployment to new artifactory

### PR DESCRIPTION
**Pull request by BClark09**
Keys have been moved across, but we are unable to verify using the GPG passphrase.

Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Comment by BClark09** [comment]
@theoweiss Would you prefer a different name than "debian-local"? It makes very little difference otherwise but I was thinking that we could use "openhab-linuxpkg" to reflect git.

**Comment by theoweiss** [comment]
@BClark09 LGTM. Sorry my spare time is totally eaten up by moving to the new house. It's all up to you and it would be great if you could take the lead on moving the snapshot release to jfrog.
Now I will look for the gpg keys at jfrog.

**Comment by theoweiss** [comment]
The gpg signing may work now. Could you test it?

**Comment by BClark09** [comment]
Awesome, thanks @theoweiss, building now.

**Comment by BClark09** [comment]
Alright! Let's see if cloudbees does the same!!

**Comment by BClark09** [comment]
All golden! Thanks a lot @theoweiss, hope the move goes well!

**Pull request merged**
