### PR TITLE
Make sure cache is removed on upgrade

### PR DESCRIPTION
**Pull request by BClark09**
Signed-off-by: Ben Clark <ben@benjyc.uk>

### CODE REVIEW

**Comment by BClark09** [comment]
@kaikreuzer, think I found our (my) our problem! Sorry for missing it earlier!

**Comment by kaikreuzer** [comment]
Ohhhh, that might actually explain many many issues of the past!
Let's hope that the "currently smoothly going upgrades" won't fail miserably now after that change! 😎

**Comment by BClark09** [comment]
Tested on my own home and it's working really well!

**Comment by AngelosF** [comment]
checked also on mine and I can confirm that apt-get upgrade on Debian Jessie clears out tmp & cache

**Pull request merged**
